// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhnpzzhlhvnsnpupvhth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhobnB6emhsaHZuc25wdXB2aHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTI3MDMsImV4cCI6MjA2MzIyODcwM30.3q2ZELyUXuUveGMqo5g4aSHsKvHwglutqUT_hdnUZ1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);